# Removed due to shiny requiring the library load
# to be explicit instead of through a helper method
# source("./utils.R")
# enforceInstallAndLoadPackage("markdown")

library("markdown")

predictorRanges <- data.frame(Cement = data.frame(min = 102, max = 350),
                              BlastFurnaceSlag = data.frame(min = 0, max = 360),
                              FlyAsh = data.frame(min = 0, max = 200),
                              Water = data.frame(min = 121, max = 247),
                              Superplasticizer = data.frame(min = 0, max = 35),
                              CoarseAggregate = data.frame(min = 801, max = 1145),
                              FineAggregate = data.frame(min = 594, max = 993),
                              Age = data.frame(min = 1, max = 365),
                              PointCount = data.frame(min = 5, max = 100))
shinyUI(
    navbarPage("Concrete Compressive Strength",
               tabPanel("Calculate",
                        sidebarLayout(
                            sidebarPanel(
                                numericInput("Cement",
                                             "Cement (kg / m^3):",
                                             min = predictorRanges$Cement.min,
                                             max = predictorRanges$Cement.max,
                                             value = 540,
                                             step = 0.5),
                                numericInput("BlastFurnaceSlag",
                                             "Blast Furnace Slag (kg / m^3):",
                                             min = predictorRanges$BlastFurnaceSlag.min,
                                             max = predictorRanges$BlastFurnaceSlag.max,
                                             value = 0,
                                             step = 0.5),
                                numericInput("FlyAsh",
                                             "Fly Ash (kg / m^3):",
                                             min = predictorRanges$FlyAsh.min,
                                             max = predictorRanges$FlyAsh.max,
                                             value = 0,
                                             step = 0.5),
                                numericInput("Water",
                                             "Water (kg / m^3):",
                                             min = predictorRanges$Water.min,
                                             max = predictorRanges$Water.max,
                                             value = 162,
                                             step = 0.5),
                                numericInput("Superplasticizer",
                                             "Superplasticizer (kg / m^3):",
                                             min = predictorRanges$Superplasticizer.min,
                                             max = predictorRanges$Superplasticizer.max,
                                             value = 2.5,
                                             step = 0.5),
                                numericInput("CoarseAggregate",
                                             "Coarse Aggregate (kg / m^3):",
                                             min = predictorRanges$CoarseAggregate.min,
                                             max = predictorRanges$CoarseAggregate.max,
                                             value = 1040,
                                             step = 0.5),
                                numericInput("FineAggregate",
                                             "Fine Aggregate (kg / m^3):",
                                             min = predictorRanges$FineAggregate.min,
                                             max = predictorRanges$FineAggregate.max,
                                             value = 676,
                                             step = 0.5),
                                numericInput("Age",
                                             "Age (day(s)):",
                                             min = predictorRanges$Age.min,
                                             max = predictorRanges$Age.max,
                                             value = 28,
                                             step = 1.0),
                                submitButton("Calculate", icon("calculator"))
                            ),
                            mainPanel(
                                h2("Concrete compressive strength (MPa):"),
                                verbatimTextOutput("CompressiveStrength")
                            )
                        )
               ),
               navbarMenu("Interactions",
                          tabPanel("Cement",
                                   sidebarLayout(
                                       sidebarPanel(
                                           sliderInput("CementSlider",
                                                       "Cement range (kg / m^3):",
                                                       min = predictorRanges$Cement.min,
                                                       max = predictorRanges$Cement.max,
                                                       value = c(predictorRanges$Cement.min, predictorRanges$Cement.max)),
                                           numericInput("Cement_BlastFurnaceSlag",
                                                        "Blast Furnace Slag (kg / m^3):",
                                                        min = predictorRanges$BlastFurnaceSlag.min,
                                                        max = predictorRanges$BlastFurnaceSlag.max,
                                                        value = 0,
                                                        step = 0.5),
                                           numericInput("Cement_FlyAsh",
                                                        "Fly Ash (kg / m^3):",
                                                        min = predictorRanges$FlyAsh.min,
                                                        max = predictorRanges$FlyAsh.max,
                                                        value = 0,
                                                        step = 0.5),
                                           numericInput("Cement_Water",
                                                        "Water (kg / m^3):",
                                                        min = predictorRanges$Water.min,
                                                        max = predictorRanges$Water.max,
                                                        value = 162,
                                                        step = 0.5),
                                           numericInput("Cement_Superplasticizer",
                                                        "Superplasticizer (kg / m^3):",
                                                        min = predictorRanges$Superplasticizer.min,
                                                        max = predictorRanges$Superplasticizer.max,
                                                        value = 2.5,
                                                        step = 0.5),
                                           numericInput("Cement_CoarseAggregate",
                                                        "Coarse Aggregate (kg / m^3):",
                                                        min = predictorRanges$CoarseAggregate.min,
                                                        max = predictorRanges$CoarseAggregate.max,
                                                        value = 1040,
                                                        step = 0.5),
                                           numericInput("Cement_FineAggregate",
                                                        "Fine Aggregate (kg / m^3):",
                                                        min = predictorRanges$FineAggregate.min,
                                                        max = predictorRanges$FineAggregate.max,
                                                        value = 676,
                                                        step = 0.5),
                                           numericInput("Cement_Age",
                                                        "Age (day(s)):",
                                                        min = predictorRanges$Age.min,
                                                        max = predictorRanges$Age.max,
                                                        value = 28,
                                                        step = 1.0),
                                           numericInput("Cement_PointCount",
                                                        "Point count:",
                                                        min = predictorRanges$PointCount.min,
                                                        max = predictorRanges$PointCount.max,
                                                        value = 25,
                                                        step = 10),
                                           submitButton("Calculate", icon("calculator"))
                                       ),
                                       mainPanel(
                                           h2("Cement interaction:"),
                                           plotOutput("CementInteractionPlot")
                                       )
                                   )
                          ),
                          tabPanel("Blast Furnace Slag",
                                   sidebarLayout(
                                       sidebarPanel(
                                           numericInput("BlastFurnaceSlag_Cement",
                                                        "Cement (kg / m^3):",
                                                        min = predictorRanges$Cement.min,
                                                        max = predictorRanges$Cement.max,
                                                        value = 540,
                                                        step = 0.5),
                                           sliderInput("BlastFurnaceSlagSlider",
                                                       "Blast Furnace Slag range (kg / m^3):",
                                                       min = predictorRanges$BlastFurnaceSlag.min,
                                                       max = predictorRanges$BlastFurnaceSlag.max,
                                                       value = c(predictorRanges$BlastFurnaceSlag.min, predictorRanges$BlastFurnaceSlag.max)),
                                           numericInput("BlastFurnaceSlag_FlyAsh",
                                                        "Fly Ash (kg / m^3):",
                                                        min = predictorRanges$FlyAsh.min,
                                                        max = predictorRanges$FlyAsh.max,
                                                        value = 0,
                                                        step = 0.5),
                                           numericInput("BlastFurnaceSlag_Water",
                                                        "Water (kg / m^3):",
                                                        min = predictorRanges$Water.min,
                                                        max = predictorRanges$Water.max,
                                                        value = 162,
                                                        step = 0.5),
                                           numericInput("BlastFurnaceSlag_Superplasticizer",
                                                        "Superplasticizer (kg / m^3):",
                                                        min = predictorRanges$Superplasticizer.min,
                                                        max = predictorRanges$Superplasticizer.max,
                                                        value = 2.5,
                                                        step = 0.5),
                                           numericInput("BlastFurnaceSlag_CoarseAggregate",
                                                        "Coarse Aggregate (kg / m^3):",
                                                        min = predictorRanges$CoarseAggregate.min,
                                                        max = predictorRanges$CoarseAggregate.max,
                                                        value = 1040,
                                                        step = 0.5),
                                           numericInput("BlastFurnaceSlag_FineAggregate",
                                                        "Fine Aggregate (kg / m^3):",
                                                        min = predictorRanges$FineAggregate.min,
                                                        max = predictorRanges$FineAggregate.max,
                                                        value = 676,
                                                        step = 0.5),
                                           numericInput("BlastFurnaceSlag_Age",
                                                        "Age (day(s)):",
                                                        min = predictorRanges$Age.min,
                                                        max = predictorRanges$Age.max,
                                                        value = 28,
                                                        step = 1.0),
                                           numericInput("BlastFurnaceSlag_PointCount",
                                                        "Point count:",
                                                        min = predictorRanges$PointCount.min,
                                                        max = predictorRanges$PointCount.max,
                                                        value = 25,
                                                        step = 10),
                                           submitButton("Calculate", icon("calculator"))
                                       ),
                                       mainPanel(
                                           h2("Blast Furnace Slag interaction:"),
                                           plotOutput("BlastFurnaceSlagInteractionPlot")
                                       )
                                   )
                          ),
                          tabPanel("Fly Ash",
                                   sidebarLayout(
                                       sidebarPanel(
                                          numericInput("FlyAsh_Cement",
                                                        "Cement (kg / m^3):",
                                                        min = predictorRanges$Cement.min,
                                                        max = predictorRanges$Cement.max,
                                                        value = 540,
                                                        step = 0.5),
                                           numericInput("FlyAsh_BlastFurnaceSlag",
                                                        "Blast Furnace Slag (kg / m^3):",
                                                        min = predictorRanges$BlastFurnaceSlag.min,
                                                        max = predictorRanges$BlastFurnaceSlag.max,
                                                        value = 0,
                                                        step = 0.5),
                                          sliderInput("FlyAshSlider",
                                                      "Fly Ash range (kg / m^3):",
                                                      min = predictorRanges$FlyAsh.min,
                                                      max = predictorRanges$FlyAsh.max,
                                                      value = c(predictorRanges$FlyAsh.min, predictorRanges$FlyAsh.max)),
                                           numericInput("FlyAsh_Water",
                                                        "Water (kg / m^3):",
                                                        min = predictorRanges$Water.min,
                                                        max = predictorRanges$Water.max,
                                                        value = 162,
                                                        step = 0.5),
                                           numericInput("FlyAsh_Superplasticizer",
                                                        "Superplasticizer (kg / m^3):",
                                                        min = predictorRanges$Superplasticizer.min,
                                                        max = predictorRanges$Superplasticizer.max,
                                                        value = 2.5,
                                                        step = 0.5),
                                           numericInput("FlyAsh_CoarseAggregate",
                                                        "Coarse Aggregate (kg / m^3):",
                                                        min = predictorRanges$CoarseAggregate.min,
                                                        max = predictorRanges$CoarseAggregate.max,
                                                        value = 1040,
                                                        step = 0.5),
                                           numericInput("FlyAsh_FineAggregate",
                                                        "Fine Aggregate (kg / m^3):",
                                                        min = predictorRanges$FineAggregate.min,
                                                        max = predictorRanges$FineAggregate.max,
                                                        value = 676,
                                                        step = 0.5),
                                           numericInput("FlyAsh_Age",
                                                        "Age (day(s)):",
                                                        min = predictorRanges$Age.min,
                                                        max = predictorRanges$Age.max,
                                                        value = 28,
                                                        step = 1.0),
                                           numericInput("FlyAsh_PointCount",
                                                        "Point count:",
                                                        min = predictorRanges$PointCount.min,
                                                        max = predictorRanges$PointCount.max,
                                                        value = 25,
                                                        step = 10),
                                           submitButton("Calculate", icon("calculator"))
                                       ),
                                       mainPanel(
                                           h2("Fly Ash interaction:"),
                                           plotOutput("FlyAshInteractionPlot")
                                       )
                                   )
                          ),
                          tabPanel("Water",
                                   sidebarLayout(
                                       sidebarPanel(
                                           numericInput("Water_Cement",
                                                        "Cement (kg / m^3):",
                                                        min = predictorRanges$Cement.min,
                                                        max = predictorRanges$Cement.max,
                                                        value = 540,
                                                        step = 0.5),
                                           numericInput("Water_BlastFurnaceSlag",
                                                        "Blast Furnace Slag (kg / m^3):",
                                                        min = predictorRanges$BlastFurnaceSlag.min,
                                                        max = predictorRanges$BlastFurnaceSlag.max,
                                                        value = 0,
                                                        step = 0.5),
                                           numericInput("Water_FlyAsh",
                                                        "Fly Ash (kg / m^3):",
                                                        min = predictorRanges$FlyAsh.min,
                                                        max = predictorRanges$FlyAsh.max,
                                                        value = 0,
                                                        step = 0.5),
                                           sliderInput("WaterSlider",
                                                       "Water range (kg / m^3):",
                                                       min = predictorRanges$Water.min,
                                                       max = predictorRanges$Water.max,
                                                       value = c(predictorRanges$Water.min, predictorRanges$Water.max)),
                                           numericInput("Water_Superplasticizer",
                                                        "Superplasticizer (kg / m^3):",
                                                        min = predictorRanges$Superplasticizer.min,
                                                        max = predictorRanges$Superplasticizer.max,
                                                        value = 2.5,
                                                        step = 0.5),
                                           numericInput("Water_CoarseAggregate",
                                                        "Coarse Aggregate (kg / m^3):",
                                                        min = predictorRanges$CoarseAggregate.min,
                                                        max = predictorRanges$CoarseAggregate.max,
                                                        value = 1040,
                                                        step = 0.5),
                                           numericInput("Water_FineAggregate",
                                                        "Fine Aggregate (kg / m^3):",
                                                        min = predictorRanges$FineAggregate.min,
                                                        max = predictorRanges$FineAggregate.max,
                                                        value = 676,
                                                        step = 0.5),
                                           numericInput("Water_Age",
                                                        "Age (day(s)):",
                                                        min = predictorRanges$Age.min,
                                                        max = predictorRanges$Age.max,
                                                        value = 28,
                                                        step = 1.0),
                                           numericInput("Water_PointCount",
                                                        "Point count:",
                                                        min = predictorRanges$PointCount.min,
                                                        max = predictorRanges$PointCount.max,
                                                        value = 25,
                                                        step = 10),
                                           submitButton("Calculate", icon("calculator"))
                                       ),
                                       mainPanel(
                                           h2("Water interaction:"),
                                           plotOutput("WaterInteractionPlot")
                                       )
                                   )
                          ),
                          tabPanel("Superplasticizer",
                                   sidebarLayout(
                                       sidebarPanel(
                                           numericInput("Superplasticizer_Cement",
                                                        "Cement (kg / m^3):",
                                                        min = predictorRanges$Cement.min,
                                                        max = predictorRanges$Cement.max,
                                                        value = 540,
                                                        step = 0.5),
                                           numericInput("Superplasticizer_BlastFurnaceSlag",
                                                        "Blast Furnace Slag (kg / m^3):",
                                                        min = predictorRanges$BlastFurnaceSlag.min,
                                                        max = predictorRanges$BlastFurnaceSlag.max,
                                                        value = 0,
                                                        step = 0.5),
                                           numericInput("Superplasticizer_FlyAsh",
                                                        "Fly Ash (kg / m^3):",
                                                        min = predictorRanges$FlyAsh.min,
                                                        max = predictorRanges$FlyAsh.max,
                                                        value = 0,
                                                        step = 0.5),
                                           numericInput("Superplasticizer_Water",
                                                        "Water (kg / m^3):",
                                                        min = predictorRanges$Water.min,
                                                        max = predictorRanges$Water.max,
                                                        value = 162,
                                                        step = 0.5),
                                           sliderInput("SuperplasticizerSlider",
                                                       "Superplasticizer range (kg / m^3):",
                                                       min = predictorRanges$Superplasticizer.min,
                                                       max = predictorRanges$Superplasticizer.max,
                                                       value = c(predictorRanges$Superplasticizer.min, predictorRanges$Superplasticizer.max)),
                                           numericInput("Superplasticizer_CoarseAggregate",
                                                        "Coarse Aggregate (kg / m^3):",
                                                        min = predictorRanges$CoarseAggregate.min,
                                                        max = predictorRanges$CoarseAggregate.max,
                                                        value = 1040,
                                                        step = 0.5),
                                           numericInput("Superplasticizer_FineAggregate",
                                                        "Fine Aggregate (kg / m^3):",
                                                        min = predictorRanges$FineAggregate.min,
                                                        max = predictorRanges$FineAggregate.max,
                                                        value = 676,
                                                        step = 0.5),
                                           numericInput("Superplasticizer_Age",
                                                        "Age (day(s)):",
                                                        min = predictorRanges$Age.min,
                                                        max = predictorRanges$Age.max,
                                                        value = 28,
                                                        step = 1.0),
                                           numericInput("Superplasticizer_PointCount",
                                                        "Point count:",
                                                        min = predictorRanges$PointCount.min,
                                                        max = predictorRanges$PointCount.max,
                                                        value = 25,
                                                        step = 10),
                                           submitButton("Calculate", icon("calculator"))
                                       ),
                                       mainPanel(
                                           h2("Superplasticizer interaction:"),
                                           plotOutput("SuperplasticizerInteractionPlot")
                                       )
                                   )
                          ),
                          tabPanel("Coarse Aggregate",
                                   sidebarLayout(
                                       sidebarPanel(
                                           numericInput("CoarseAggregate_Cement",
                                                        "Cement (kg / m^3):",
                                                        min = predictorRanges$Cement.min,
                                                        max = predictorRanges$Cement.max,
                                                        value = 540,
                                                        step = 0.5),
                                           numericInput("CoarseAggregate_BlastFurnaceSlag",
                                                        "Blast Furnace Slag (kg / m^3):",
                                                        min = predictorRanges$BlastFurnaceSlag.min,
                                                        max = predictorRanges$BlastFurnaceSlag.max,
                                                        value = 0,
                                                        step = 0.5),
                                           numericInput("CoarseAggregate_FlyAsh",
                                                        "Fly Ash (kg / m^3):",
                                                        min = predictorRanges$FlyAsh.min,
                                                        max = predictorRanges$FlyAsh.max,
                                                        value = 0,
                                                        step = 0.5),
                                           numericInput("CoarseAggregate_Water",
                                                        "Water (kg / m^3):",
                                                        min = predictorRanges$Water.min,
                                                        max = predictorRanges$Water.max,
                                                        value = 162,
                                                        step = 0.5),
                                           numericInput("CoarseAggregate_Superplasticizer",
                                                        "Superplasticizer (kg / m^3):",
                                                        min = predictorRanges$Superplasticizer.min,
                                                        max = predictorRanges$Superplasticizer.max,
                                                        value = 2.5,
                                                        step = 0.5),
                                           sliderInput("CoarseAggregateSlider",
                                                       "Coarse Aggregate range (kg / m^3):",
                                                       min = predictorRanges$CoarseAggregate.min,
                                                       max = predictorRanges$CoarseAggregate.max,
                                                       value = c(predictorRanges$CoarseAggregate.min, predictorRanges$CoarseAggregate.max)),
                                           numericInput("CoarseAggregate_FineAggregate",
                                                        "Fine Aggregate (kg / m^3):",
                                                        min = predictorRanges$FineAggregate.min,
                                                        max = predictorRanges$FineAggregate.max,
                                                        value = 676,
                                                        step = 0.5),
                                           numericInput("CoarseAggregate_Age",
                                                        "Age (day(s)):",
                                                        min = predictorRanges$Age.min,
                                                        max = predictorRanges$Age.max,
                                                        value = 28,
                                                        step = 1.0),
                                           numericInput("CoarseAggregate_PointCount",
                                                        "Point count:",
                                                        min = predictorRanges$PointCount.min,
                                                        max = predictorRanges$PointCount.max,
                                                        value = 25,
                                                        step = 10),
                                           submitButton("Calculate", icon("calculator"))   
                                       ),
                                       mainPanel(
                                           h2("Coarse Aggregate interaction:"),
                                           plotOutput("CoarseAggregateInteractionPlot")
                                       )
                                   )
                          ),
                          tabPanel("Fine Aggregate",
                                   sidebarLayout(
                                       sidebarPanel(
                                           numericInput("FineAggregate_Cement",
                                                        "Cement (kg / m^3):",
                                                        min = predictorRanges$Cement.min,
                                                        max = predictorRanges$Cement.max,
                                                        value = 540,
                                                        step = 0.5),
                                           numericInput("FineAggregate_BlastFurnaceSlag",
                                                        "Blast Furnace Slag (kg / m^3):",
                                                        min = predictorRanges$BlastFurnaceSlag.min,
                                                        max = predictorRanges$BlastFurnaceSlag.max,
                                                        value = 0,
                                                        step = 0.5),
                                           numericInput("FineAggregate_FlyAsh",
                                                        "Fly Ash (kg / m^3):",
                                                        min = predictorRanges$FlyAsh.min,
                                                        max = predictorRanges$FlyAsh.max,
                                                        value = 0,
                                                        step = 0.5),
                                           numericInput("FineAggregate_Water",
                                                        "Water (kg / m^3):",
                                                        min = predictorRanges$Water.min,
                                                        max = predictorRanges$Water.max,
                                                        value = 162,
                                                        step = 0.5),
                                           numericInput("FineAggregate_Superplasticizer",
                                                        "Superplasticizer (kg / m^3):",
                                                        min = predictorRanges$Superplasticizer.min,
                                                        max = predictorRanges$Superplasticizer.max,
                                                        value = 2.5,
                                                        step = 0.5),
                                           numericInput("FineAggregate_CoarseAggregate",
                                                        "Coarse Aggregate (kg / m^3):",
                                                        min = predictorRanges$CoarseAggregate.min,
                                                        max = predictorRanges$CoarseAggregate.max,
                                                        value = 1040,
                                                        step = 0.5),
                                           sliderInput("FineAggregateSlider",
                                                       "FineAggregate range (kg / m^3):",
                                                       min = predictorRanges$FineAggregate.min,
                                                       max = predictorRanges$FineAggregate.max,
                                                       value = c(predictorRanges$FineAggregate.min, predictorRanges$FineAggregate.max)),
                                           numericInput("FineAggregate_Age",
                                                        "Age (day(s)):",
                                                        min = predictorRanges$Age.min,
                                                        max = predictorRanges$Age.max,
                                                        value = 28,
                                                        step = 1.0),
                                           numericInput("FineAggregate_PointCount",
                                                        "Point count:",
                                                        min = predictorRanges$PointCount.min,
                                                        max = predictorRanges$PointCount.max,
                                                        value = 25,
                                                        step = 10),
                                           submitButton("Calculate", icon("calculator")) 
                                       ),
                                       mainPanel(
                                           h2("Fine Aggregate interaction:"),
                                           plotOutput("FineAggregateInteractionPlot")
                                       )
                                   )
                          ),
                          tabPanel("Age",
                                   sidebarLayout(
                                       sidebarPanel(
                                           numericInput("Age_Cement",
                                                        "Cement (kg / m^3):",
                                                        min = predictorRanges$Cement.min,
                                                        max = predictorRanges$Cement.max,
                                                        value = 540,
                                                        step = 0.5),
                                           numericInput("Age_BlastFurnaceSlag",
                                                        "Blast Furnace Slag (kg / m^3):",
                                                        min = predictorRanges$BlastFurnaceSlag.min,
                                                        max = predictorRanges$BlastFurnaceSlag.max,
                                                        value = 0,
                                                        step = 0.5),
                                           numericInput("Age_FlyAsh",
                                                        "Fly Ash (kg / m^3):",
                                                        min = predictorRanges$FlyAsh.min,
                                                        max = predictorRanges$FlyAsh.max,
                                                        value = 0,
                                                        step = 0.5),
                                           numericInput("Age_Water",
                                                        "Water (kg / m^3):",
                                                        min = predictorRanges$Water.min,
                                                        max = predictorRanges$Water.max,
                                                        value = 162,
                                                        step = 0.5),
                                           numericInput("Age_Superplasticizer",
                                                        "Superplasticizer (kg / m^3):",
                                                        min = predictorRanges$Superplasticizer.min,
                                                        max = predictorRanges$Superplasticizer.max,
                                                        value = 2.5,
                                                        step = 0.5),
                                           numericInput("Age_CoarseAggregate",
                                                        "Coarse Aggregate (kg / m^3):",
                                                        min = predictorRanges$CoarseAggregate.min,
                                                        max = predictorRanges$CoarseAggregate.max,
                                                        value = 1040,
                                                        step = 0.5),
                                           numericInput("Age_FineAggregate",
                                                        "Fine Aggregate (kg / m^3):",
                                                        min = predictorRanges$FineAggregate.min,
                                                        max = predictorRanges$FineAggregate.max,
                                                        value = 676,
                                                        step = 0.5),
                                           sliderInput("AgeSlider",
                                                       "Age range (day(s)):",
                                                       min = predictorRanges$Age.min,
                                                       max = predictorRanges$Age.max,
                                                       value = c(predictorRanges$Age.min, predictorRanges$Age.max)),
                                           numericInput("Age_PointCount",
                                                        "Point count:",
                                                        min = predictorRanges$PointCount.min,
                                                        max = predictorRanges$PointCount.max,
                                                        value = 25,
                                                        step = 10),
                                           submitButton("Calculate", icon("calculator"))
                                       ),
                                       mainPanel(
                                           h2("Age interaction:"),
                                           plotOutput("AgeInteractionPlot")
                                       )
                                   )
                          )
               ),
               tabPanel("Model fit details",
                        mainPanel(
                            h3("R-Squared: "),
                            textOutput("rSquaredValue"),
                            h3("RMSE: "),
                            textOutput("rmseValue"),
                            h3("Neural net graph:"),
                            plotOutput(outputId = "NeuralNetPlot", width = "100%"),
                            h3("Predictor importance:"),
                            plotOutput("GarsonPlot")
                        )
               ),
               tabPanel("About",
                        mainPanel(
                            includeMarkdown("about.md")
                        )
               )
    )
)